### ISSUE TITLE
distance.m function is missing

### ISSUE THREAD

**Issue by thaboub** [JustMeZXX/Multi-Modal-Sensor-Fusion-for-Acoustic-Exploration-of-Aircraft-Signals#1]
Hi Dear,  
Thank you very much for posting such great code for fusing different sensor modalities. I am wondering if possible, if you could provide me with "distance.m" function, as I run the “code_01_synchronization.m ”, it generates an error:

Undefined function 'distance' for input arguments of type 'double'. 
Error in code_01_synchronization (line 111[arclen,az] =  distance(lat,lon,reflat*ones(size(lat)),reflon*ones(size(lon)),'degrees');

Thank you very much
Haboub

**Comment by JustMeZXX** [comment]
Thanks for pointing this out. 

The distance function is a built-in function from Matlab, see https://www.mathworks.com/help/map/ref/distance.html. If you are seeing the errors, please update your Matlab version to R2022b (same as mine) or newer. Thank you!
